### ISSUE TITLE
Date field - Unknown column 'time' in 'field list'

### ISSUE THREAD

**Issue by nathanhornby** [symphonycms/symphony-2#2474]
**Symphony 2.6.2**

I just created a section with a date field and received this error:

> Unknown column 'time' in 'field list'
> INSERT INTO `sym_fields_date` (`pre_populate`, `time`, `calendar`, `field_id`) VALUES ('now', 'no', 'no', '76')

The section seems to work fine after creation - aside from there being no time in the date field value (whether I set it or not).

Was this a change to the field that isn't expected by some part of the backend? Or is it isolated to the field itself?

(sorry wasn't sure where to report the issue, it being a core extension!)

**Comment by brendo** [comment]
There's a migration for [2.6.0](https://github.com/symphonycms/symphony-2/blob/master/install/migrations/2.6.0.php#L20-L24) that will add these columns on update. Do you remember if the migrations were run in this environment?

**Comment by nathanhornby** [comment]
Hi @Brendo - this was a fresh install for a new project a couple days ago!

**Comment by brendo** [comment]
Ah got it. It's two conflicting `install.sql` files, the [installer](https://github.com/symphonycms/symphony-2/blob/master/install/includes/install.sql#L118-L128) and the [workspace installer](https://github.com/symphonycms/workspace/blob/master/install.sql#L30-L38) when running from the ensemble.

Good pickup, a little scary it hasn't been reported for 18 months!

**Comment by nathanhornby** [comment]
That long?? Blimey - surprised I haven't run into it a few times since then!

**Comment by brendo** [comment]
I've fixed the [workspace](https://github.com/symphonycms/workspace/commit/81f261c5257fd281bdbefaa9f32e3f1a233a42f4) and this will be pushed up as part of the 2.6.3 release.

**Comment by nathanhornby** [comment]
Sweet, thanks @Brendo!

**Comment by andrewminton** [comment]
Just came across this issue from a fresh install of the blog ensemble. The 2.6.0 migration for the date field did not seem to run and hence got the same error that Nathan had.

**Comment by nitriques** [comment]
Does it needs fixing ?

**Comment by andrewminton** [comment]
I couldn't determine where it was failing. May be worth pulling the
ensemble from the main getsymphony.com website again and checking if this
error still exists. Upon saving a section containing a date field. It would
fail, I then manually applied the sql patch from the 2.6.0 migration file
@brendo mentioned.

**Comment by nitriques** [comment]
Hum I sadly do not have enough time to check an issue in an ensemble.
